services:
  rocker:
    build:
      dockerfile: ./.devcontainer/Dockerfile
    container_name: rocker-starter
    environment:
      - DISABLE_AUTH=true
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio
    working_dir: /home/rstudio
